language: java
deploy:
  provider: heroku
  app: supermarketapp-gowtham
  api_key:
    secure: "011242fb-40a4-4981-b1cf-03eea5b46b27"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
